# Generated by Django 4.2.30 on 2026-09-05 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remap_old_privacy_values(apps, schema_editor):
    """v8 reworks board privacy from 3 options to 4. Map the old stored
    values onto their closest new equivalent:
      'friends' (friends could see/join) -> 'all_friends'
      'invite'  (owner adds manually)    -> 'members'
      'private' (just me)                -> 'private' (unchanged)
    """
    Group = apps.get_model('core', 'Group')
    Group.objects.filter(privacy='friends').update(privacy='all_friends')
    Group.objects.filter(privacy='invite').update(privacy='members')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_v8_tweaks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("private", "Just me"),
                    ("members", "Only members"),
                    ("friend_group", "A specific friend group"),
                    ("all_friends", "All my friends"),
                ],
                default="members",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="location_name",
            field=models.CharField(blank=True, help_text="Place name", max_length=255),
        ),
        migrations.AlterField(
            model_name="memory",
            name="memory_date",
            field=models.DateField(
                blank=True, help_text="When did this happen?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("reaction", "Reaction on memory"),
                    ("comment", "Comment on memory"),
                    ("tag", "Tagged in memory"),
                    ("friend_req", "Friend request"),
                    ("board_invite", "Board invitation"),
                    ("pin", "Memory pinned"),
                    ("board_visible", "Board shared with you"),
                    ("join_request", "Board join request"),
                    ("join_approved", "Join request approved"),
                    ("on_this_day", "On this day memories"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FriendGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="friend_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="visible_to_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visible_boards",
                to="core.friendgroup",
            ),
        ),
        migrations.CreateModel(
            name="BoardJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="core.group",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("board", "requester")},
            },
        ),
        migrations.RunPython(remap_old_privacy_values, noop_reverse),
    ]
