# Generated by Django 4.2.30 on 2026-09-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_v8_social"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(
                blank=True, help_text="A short line about you", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="info_visibility",
            field=models.CharField(
                choices=[("friends", "Visible to friends"), ("private", "Only me")],
                default="friends",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
