# Generated by Django 4.2.30 on 2026-09-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_userprofile_bio_userprofile_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvite",
            name="invited_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_board_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("reaction", "Reaction on memory"),
                    ("comment", "Comment on memory"),
                    ("tag", "Tagged in memory"),
                    ("friend_req", "Friend request"),
                    ("board_invite", "Board invitation"),
                    ("board_invite_pending", "Board invitation (needs a response)"),
                    ("pin", "Memory pinned"),
                    ("board_visible", "Board shared with you"),
                    ("join_request", "Board join request"),
                    ("join_approved", "Join request approved"),
                    ("on_this_day", "On this day memories"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FriendInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("from_user", "email")},
            },
        ),
    ]
