# Generated by Django 4.2.30 on 2026-09-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_groupinvite_invited_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="memories/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_photos",
                        to="core.memory",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
