# Generated by Django 4.2.30 on 2026-09-06 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_memoryphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Members promoted by the owner to help manage this board.",
                related_name="admin_boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="memory_videos/"),
        ),
        migrations.AddField(
            model_name="memory",
            name="voice_note",
            field=models.FileField(blank=True, null=True, upload_to="memory_voice/"),
        ),
    ]
