# Generated by Django 4.2.30 on 2026-09-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_group_admins_memory_video_memory_voice_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="share_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="share_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
