# Generated by Django 4.2.30 on 2026-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_group_share_token_memory_share_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("system", "Match system"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="light",
                max_length=10,
            ),
        ),
    ]
