# Generated by Django 4.2.30 on 2026-09-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="cover_focal_y",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_seen_home_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
