# Generated by Django 4.2.30 on 2026-09-08 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_group_cover_focal_y_userprofile_last_seen_home_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="board_sort_mode",
            field=models.CharField(
                choices=[
                    ("recent", "Most recently updated"),
                    ("alphabetical", "Alphabetical"),
                    ("custom", "Custom"),
                ],
                default="recent",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="BoardOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("sort_order", models.FloatField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_orders",
                        to="core.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "group")},
            },
        ),
    ]
