# Generated by Django 4.2.30 on 2026-09-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_userprofile_board_sort_mode_boardorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("disabled", "Disabled"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
