# Generated by Django 4.2.30 on 2026-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_userprofile_account_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("el", "Ελληνικά")],
                default="en",
                max_length=10,
            ),
        ),
    ]
