# Generated by Django 4.2.30 on 2026-10-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_memoryreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="note_font",
            field=models.CharField(
                choices=[
                    ("dm_sans", "DM Sans"),
                    ("comfortaa", "Comfortaa"),
                    ("lora", "Lora"),
                    ("caveat", "Caveat"),
                    ("courier_prime", "Courier Prime"),
                    ("patrick_hand", "Patrick Hand"),
                ],
                default="dm_sans",
                max_length=20,
            ),
        ),
    ]
