# Generated by Django 4.2.30 on 2026-10-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_userprofile_note_font"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_board_privacy",
            field=models.CharField(
                choices=[
                    ("private", "Just me"),
                    ("members", "Only members"),
                    ("friend_group", "A specific friend group"),
                    ("all_friends", "All my friends"),
                ],
                default="members",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_friend_request",
            field=models.BooleanField(default=False),
        ),
    ]
